#!/bin/sh

# Variables

# General
NOT_INSTALLED_ICON="✗"
PUBLIC_IP=""
UBUNTU_VERSION=""
UBUNTU_GREATER=false

# Icons
WEBSERVER_ICON=$NOT_INSTALLED_ICON
NGINX_ICON=$NOT_INSTALLED_ICON
NODE_ICON=$NOT_INSTALLED_ICON
MONGODB_ICON=$NOT_INSTALLED_ICON
LETSENCRYPT_ICON=$NOT_INSTALLED_ICON